services:
  pool_api:
    image: pool_api
    container_name: pool_api
    build:
      context: .
      dockerfile: src/pool_api/Dockerfile
    command: uvicorn src.pool_api.api.application:get_app --host 0.0.0.0 --port 8000 --workers 1
    ports:
      - target: 8000
        host_ip: 127.0.0.1
        published: 8501
        protocol: tcp
        mode: host
    networks:
      - python_core
  
  postgres_db:
    image: postgres
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
      POSTGRES_DB: local
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - target: 5432
        host_ip: 127.0.0.1
        published: 5432
        protocol: tcp
        mode: host
    networks:
      - python_core

  redis:
    image: redis
    container_name: redis
    restart: always
    networks:
      - python_core
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - target: 6379
        host_ip: 127.0.0.1
        published: 6379
        protocol: tcp
        mode: host

networks:
  python_core:
    name: python_core
