py_binary(
    name = "calculate_statistics",
    srcs = ["main.py"],
    main = "main.py",
    visibility = ["//visibility:public"],
    args = [
        "-f /Users/lap14443/Projects/Python-Core/src/calculate_statistics/weather_stations.csv",
    ]
)
