# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python-Core

on:
  push

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Validate ref_name
      run: |
        make check_ref_name REF_TYPE=${{ github.ref_type }} REF_NAME=${{ github.ref_name }}
    - name: List files in the repository
      run: |
        cd ${{ github.workspace }}
        pwd
        ls -lah ./
    - uses: bazelbuild/setup-bazelisk@v3
    - name: Get changed files
      id: changed-files
      uses: jitterbit/get-changed-files@v1
      with:
        format: 'csv'
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Run CI
      id: run-ci
      run: |
        make run_ci CHANGES=${{ steps.changed-files.outputs.all }}
