# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python-Core

on:
  push

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Validate ref_name
      run: |
        bash convention_checking.sh REF ${{ github.ref_type }} ${{ github.ref_name }}
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python3 --version
        python3 -m pip install --upgrade pip
        pip install -r ./requirements.txt
    - name: List files in the repository
      run: |
        cd ${{ github.workspace }}
        pwd
        ls -lah ./
    - name: Convention checking
      run: |
        git branch -l
        git log | head -n 5
        python3 src/git_python/git_ci.py -f skip_convention_checking -c ${{ github.sha }}
        # Check PEP8
        bash convention_checking.sh PEP8
        # Run unit tests
        bash convention_checking.sh TEST
