# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python-Core

on:
  push

permissions:
  contents: read

env:
  ENVIRONMENT: dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Validate ref_name
      run: |
        make check_ref_name REF_TYPE=${{ github.ref_type }} REF_NAME=${{ github.ref_name }}

    - name: Setup Bazel
      id: setup-bazel
      uses: bazelbuild/setup-bazelisk@v3

    - name: Get changed files
      id: changed-files
      continue-on-error: true
      uses: jitterbit/get-changed-files@v1
      with:
        format: 'csv'

    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"

    - name: Verify changes
      id: verify-changes
      run: |
        pattern="^test-all-v.*"
        if [ "${{ github.ref_type }}" == "tag" ] && [[ "${{ github.ref_name }}" =~ ${pattern} ]];
        then
          make test_all
        else
          make verify_changes CHANGES=${{ steps.changed-files.outputs.all }}
        fi
